twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['_layouts/form.html.twig']
    globals:
        NavigationService: '@App\Services\NavigationService'
        ProductRepository: '@App\Repository\ProductRepository'
        CategoryRepository: '@App\Repository\CategoryRepository'
        CartManager: '@App\Services\Shop\CartManager'
