twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['_layouts/form.html.twig']
    globals:
        NavigationService: '@App\Services\NavigationService'
        ProductService: '@App\Services\Shop\ProductService'
        CategoryService: '@App\Services\Shop\CategoryService'
        CartManager: '@App\Services\Shop\CartManagement\CartManagerInterface'
