version: '3'

services:
    chrome:
        image: selenium/standalone-chrome
    nginx:
        image: nginx:alpine
        ports:
            - ${DOCKER_APP_PORT}:80
        volumes:
            - .:${DOCKER_PROJECT_PATH}
            - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - php
        environment:
            - DOCKER_PROJECT_PATH=${DOCKER_PROJECT_PATH}
            - PHP_SERVICE=php
    php:
        image: farpat/myphp:7.4
        volumes:
            - .:${DOCKER_PROJECT_PATH}
            - ~/.cache/composer:/.cache/composer
        working_dir: ${DOCKER_PROJECT_PATH}
        depends_on:
            - mariadb
            - maildev
            - redis
    redis:
        image: redis:5-alpine
    mariadb:
        image: mariadb
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret

volumes:
    db_data:
        driver: local
