version: '3'

services:
    chrome:
        image: selenium/standalone-chrome
    nginx:
        image: nginx:alpine
        ports:
            - ${APP_PORT}:80
        volumes:
            - .:${PROJECT_PATH}
            - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - php
        environment:
            - PROJECT_PATH=${PROJECT_PATH}
            - PHP_SERVICE=php
    php:
        image: farpat/myphp:7.4
        volumes:
            - .:${PROJECT_PATH}
            - ~/.cache/composer:/.cache/composer
        working_dir: ${PROJECT_PATH}
        depends_on:
            - mariadb
            - maildev
            - redis
    redis:
        image: redis:5-alpine
    mariadb:
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
    webpack_dev_server:
        image: farpat/mynode
        ports:
            - ${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}
        volumes:
            - .:${PROJECT_PATH}
        working_dir: ${PROJECT_PATH}
        command: npm run dev

volumes:
    db_data:
        driver: local