version: '3'

services:
  chrome:
    build: ./docker/chrome
  nginx_dev:
    build: ./docker/nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:${PROJECT_PATH}
      - ./docker/nginx/nginx.sh:/var/nginx.sh
      - ./docker/nginx/sites-enabled:/var/sites-enabled
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php_dev
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
      - PHP_SERVICE=php_dev
    command: ./var/nginx.sh
  nginx_dusk:
    build: ./docker/nginx
    volumes:
      - .:${PROJECT_PATH}
      - ./docker/nginx/nginx.sh:/var/nginx.sh
      - ./docker/nginx/sites-enabled:/var/sites-enabled
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php_dusk
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
      - PHP_SERVICE=php_dusk
    command: ./var/nginx.sh
  php_dev:
    build: ./docker/php
    volumes:
      - .:${PROJECT_PATH}
      - ~/.cache/composer:/.cache/composer
    working_dir: ${PROJECT_PATH}
    depends_on:
      - mariadb
      - maildev
      - redis
  php_dusk:
    build: ./docker/php
    volumes:
      - .:${PROJECT_PATH}
      - ~/.cache/composer:/.cache/composer
    working_dir: ${PROJECT_PATH}
    depends_on:
      - chrome
      - mariadb
      - maildev
      - redis
  redis:
    build: ./docker/redis
  mariadb:
    build: ./docker/mariadb
    ports:
      - "3306:3306"
    volumes:
      - /var/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
  webpack_dev_server:
    build: ./docker/node
    ports:
      - "${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}"
    volumes:
      - .:${PROJECT_PATH}
    working_dir: ${PROJECT_PATH}
    command: "npm run dev"
