version: '3'

services:
    chrome:
        image: selenium/standalone-chrome
    nginx:
        image: nginx:alpine
        ports:
            - ${APP_PORT}:80
        volumes:
            - .:${PROJECT_PATH}
            - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - php
        environment:
            - PROJECT_PATH=${PROJECT_PATH}
            - PHP_SERVICE=php
    php:
        build: ./docker/php
        volumes:
            - .:${PROJECT_PATH}
            - ~/.cache/composer:/.cache/composer
        working_dir: ${PROJECT_PATH}
        depends_on:
            - postgres
            - maildev
            - redis
    redis:
        image: redis:5-alpine
    postgres:
        image: postgres:12-alpine
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: farrugia
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: shop_symfony
    maildev:
        image: maildev/maildev:2.0.0-beta3
        ports:
            - 1080:80
    webpack_dev_server:
        image: node:14-alpine
        ports:
            - ${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}
        volumes:
            - .:${PROJECT_PATH}
        working_dir: ${PROJECT_PATH}
        command: npm run dev

volumes:
    db_data:
        driver: local