version: '3'

services:
    chrome:
        build: ./docker/chrome
    nginx:
        build: ./docker/nginx
        ports:
            - ${APP_PORT}:80
        volumes:
            - .:${PROJECT_PATH}
            - ./docker/nginx/nginx.sh:/var/nginx.sh
            - ./docker/nginx/sites-enabled:/var/sites-enabled
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        environment:
            - PROJECT_PATH=${PROJECT_PATH}
            - PHP_SERVICE=php
        command: ./var/nginx.sh
    php:
        build: ./docker/php
        volumes:
            - .:${PROJECT_PATH}
            - ~/.cache/composer:/.cache/composer
        working_dir: ${PROJECT_PATH}
        depends_on:
            - mariadb
            - maildev
            - redis
    redis:
        build: ./docker/redis
    mariadb:
        build: ./docker/mariadb
        ports:
            - 3306:3306
        volumes:
            - /var/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    maildev:
        image: djfarrelly/maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 1080:80
    webpack_dev_server:
        build: ./docker/node
        ports:
            - ${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}
        volumes:
            - .:${PROJECT_PATH}
        working_dir: ${PROJECT_PATH}
        command: npm run dev
