version: '3'

services:
    nginx:
        image: nginx:alpine
        ports:
            - ${DOCKER_APP_PORT}:80
        volumes:
            - .:${DOCKER_PROJECT_PATH}
            - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - php
        environment:
            - DOCKER_PROJECT_PATH=${DOCKER_PROJECT_PATH}
            - PHP_SERVICE=php
    php:
        image: farpat/myphp:7.4
        volumes:
            - .:${DOCKER_PROJECT_PATH}
            - ~/.cache/composer:/.cache/composer
        working_dir: ${DOCKER_PROJECT_PATH}
        user: app
        depends_on:
            - mariadb
            - maildev
            - redis
    redis:
        image: redis:5-alpine
    mariadb:
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
    maildev:
        image: maildev/maildev:2.0.0-beta3
        ports:
            - 1080:1080
    asset_dev_server:
        image: farpat/mynode
        ports:
            - ${DOCKER_ASSET_DEV_SERVER_PORT}:${DOCKER_ASSET_DEV_SERVER_PORT}
        volumes:
            - .:${DOCKER_PROJECT_PATH}
        working_dir: ${DOCKER_PROJECT_PATH}
        command: ./node_modules/.bin/encore dev-server --hot --public http://localhost:3000 --host 0.0.0.0 --port 3000

volumes:
    db_data:
        driver: local